credit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('private/2803', admin.site.urls),
	path('', include('web.urls')),
]

web/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'web'

urlpatterns = [
        path('', views.main, name='main'),
        path('new_form', views.new_form, name='new_form'),
        path('login', views.login, name='login'),
        path('logout', views.logout, name='logout'),
        path('admin/<int:form_pk>', views.form_view, name='form_view'),
        path('admin', views.list, name='list'),
        path('admin/<int:form_pk>/delete', views.form_delete, name='form_delete'),
        path('admin/form_delete_all', views.form_delete_all, name='form_delete_all'),
        path('admin/file_delete',views.file_delete, name='file_delete'),
        path('admin/file_delete_all',views.file_delete_all, name='file_delete_all'),
        path('admin/file_view',views.file_view, name='file_view'),
        path('admin/edit',views.file_edit, name='file_edit'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/web/file_view.html
{%extends 'web/list_base.html'%}
{%load static%}
{%block content%}
<div class="file_text">
  <h1>파일명 : {{file_name}}</h1>
  <form class="file_delete_btn" name="file_delete_btn" action="{%url 'web:file_delete'%}" method="post">
    {%csrf_token%}
    <input style="display:none;" type="text" name="file_name" value="{{file_name}}">
    <button type="submit">삭제</button>
  </form>
  <form class="file_edit_btn" name="file_edit_btn" action="{%url 'web:file_edit'%}" method="post" onsubmit="return validate_edit();">
    {%csrf_token%}
    <input style="display:none;" type="text" name="file_name" value="{{file_name}}">
    <input id="file_new_name" type="text" name="file_new_name" placeholder="파일명 입력">
    <button type="submit">수정</button>
  </form>
  <br><br>
  <p>
    {%for line in text%}
      {{line|linebreaksbr}}
    {%endfor%}
  </p>
</div>
{%endblock%}

web/templates/web/form_base.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="{%static 'web/js/validate.js'%}"></script>
    <link rel="stylesheet" href="{%static 'web/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/form_base.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/main.css'%}">
    <title>비대면심사 신청</title>
  </head>
  <body>

    <section id = "first_section">
      <div class="header_box">
        <img src="{%static 'web/img/icon.png'%}">
        <h1>개인대출 비대면심사 중개</h1>
      </div>
    </section>

    <section id="second_section">
      {%block content%}
      {%endblock%}
    </section>

    <section id="third_section">
      <div class="info_box">
        <p>개인대출 심사시 해당 대부업체의 심사팀으로 양식이 이동되며 심사시 신용등급 또는 신용점수에 지장이나 어떠한 불이익도 받지 않습니다.</p>
        <br>
        <p>과도한 빚은 당신에게 큰 불행을 안겨줄 수 있습니다. 중개수수료를 요구하거나 받는 것은 불법입니다.</p>
      </div>
    </section>

  </body>
</html>

web/templates/web/form_view.html
{%extends 'web/list_base.html'%}
{%load static%}
{%block content%}
  <div class="form_view_box">
    <table class="form_view_table">
        <tr>
          <th>신청날짜</th>
          <th>{{form.date}}</th>
        </tr>
        <tr>
          <th>이름</th>
          <th>{{form.name}}</th>
        </tr>
        <tr>
          <th>전화번호</th>
          <th>{{form.phone_number}}</th>
        </tr>
        <tr>
          <th>주소</th>
          <th>{{form.region}}</th>
        </tr>
        <tr>
          <th>나이</th>
          <th>{{form.age}}세</th>
        </tr>
        <tr>
          <th>성별</th>
          <th>
            {%if form.gender == 'man'%}
            남자
            {%else%}
            여자
            {%endif%}
          </th>
        </tr>
        <tr>
          <th>직업</th>
          <th>{{form.job}}</th>
        </tr>
        <tr>
          <th>급여</th>
          <th>{{form.pay}}만원</th>
        </tr>
        <tr>
          <th>급여날짜</th>
          <th>매달 {{form.pay_day}}일</th>
        </tr>
        <tr>
          <th>개인돈 사용여부</th>
          <th>
            {%if form.use_bool == 'yes'%}
            있음
            {%else%}
            없음
            {%endif%}
          </th>
        </tr>
        <tr>
          <th>개인돈 사용내역</th>
          <th>{{form.use_ps|linebreaks}}</th>
        </tr>
        <tr>
          <th>신용등급</th>
          <th>{{form.credit_grade}}등급</th>
        </tr>
        <tr>
          <th>기대출</th>
          <th>
            {%if form.holding_credit == 0%}
            없음
            {%else%}
            {{form.holding_credit}}만원
            {%endif%}
          </th>
        </tr>
        <tr>
          <th>자동차 보유</th>
          <th>
            {%if form.holding_car == 'yes'%}
            있음
            {%else%}
            없음
            {%endif%}
          </th>
        </tr>
        <tr>
          <th>거주 형태</th>
          <th>
            {%if form.holding_house == 'charter'%}
            전세
            {%elif form.holding_house == 'monthly'%}
            월세
            {%else%}
            자가
            {%endif%}
          </th>
        </tr>
        <tr>
          <th>대출신청금</th>
          <th>{{form.credit_amount}}만원</th>
        </tr>
        <tr>
          <th>원하는 상환방식</th>
          <th>
            {%if form.credit_date == 'daily'%}
            일수
            {%elif form.credit_date == 'monthly'%}
            월변
            {%else%}
            주변
            {%endif%}
          </th>
        </tr>

    </table>

  </div>
{%endblock%}

web/templates/web/list.html
{%extends 'web/list_base.html'%}
{%load static%}
{%load  custom_tag%}
{%block content%}
<section id="list_section">
<section id="first_section">
  <div class="list_box">
    <br><br>
    <h1><신청목록></h1>
    <br><br>
    <a class="form_delete_all_btn" onclick="return delete_all_check('신청');" href="{%url 'web:form_delete_all'%}">전체삭제</a>
    <br><br><br><br>
    {%for form in forms%}
      <a class="form_link" href="{%url 'web:form_view' form_pk=form.pk%}">[{{forloop.revcounter}}] {{form.date}} // {{form.name|text_slice}} // {{form.age}}세 // {{form.phone_number}} // {{form.region|text_slice}} // {{form.credit_amount}}필요</a>
      <a class="form_delete_btn" href="{%url 'web:form_delete' form_pk=form.pk%}">삭제</a>
      <br><br>
    {%endfor%}
  </div>
</section>
<section id="second_section">
  <br><br>
  <h1><파일목록></h1>
  <br><br>
  <div class="list_box">
    <a class="file_delete_all_btn" onclick="return delete_all_check('파일');" href="{%url 'web:file_delete_all'%}">전체삭제</a>
    <br><br><br><br>
    {%for time_arr,time_sorted_txt_list in zip_file%}
      <form class="file_view_btn" name="file_view_btn" action="{%url 'web:file_view'%}" method="post">
        {%csrf_token%}
        <input style="display:none;" type="text" name="file_name" value="{{time_sorted_txt_list}}">
        <button type="submit">[{{forloop.revcounter}}] {{time_arr}} {{time_sorted_txt_list}}</button>
      </form>
      <form class="file_delete_btn" name="file_delete_btn" action="{%url 'web:file_delete'%}" method="post">
        {%csrf_token%}
        <input style="display:none;" type="text" name="file_name" value="{{time_sorted_txt_list}}">
        <button type="submit">삭제</button>
      </form>
      <br><br>
    {%endfor%}
  </div>
</section>
</section>
{%endblock%}

web/templates/web/list_base.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="{%static 'web/js/validate.js'%}"></script>
    <script type="text/javascript" src="{%static 'web/js/btn.js'%}"></script>
    <link rel="stylesheet" href="{%static 'web/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/list_base.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/list.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/form_view.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/file_view.css'%}">
    <title>관리페이지</title>
  </head>
  <body>
    <section id="header_section">
      <div class="header_box">
        <a class="renew_btn" href="{%url 'web:list'%}">관리페이지</a>
        <p>* 새로고침하시면 DB가 업데이트 됩니다.     * 종료시 보안상 무조건 로그아웃 및 해당 브라우저의 인터넷 사용기록과 쿠키를 삭제하세요.</p>
        <a class="logout_btn" href="{%url 'web:logout'%}">로그아웃</a>
      </div>
    </section>
    {%block content%}
    {%endblock%}
  </body>

web/templates/web/login.html
{%load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script type="text/javascript" src="{%static 'web/js/validate.js'%}"></script>
    <link rel="stylesheet" href="{%static 'web/css/reset.css'%}">
    <link rel="stylesheet" href="{%static 'web/css/login.css'%}">
    <title>로그인</title>
  </head>
  <body>
  <div class="login_box">
    <form action="{%url 'web:login'%}" method="post"
    onsubmit="return validate_login();">
    {%csrf_token%}
      <input id="user_id" type="text" name="user_id" placeholder="아이디 입력">
      <br><br>
      <input id="user_pw" type="password" name="user_pw" placeholder="비밀번호 입력">
      <br><br>
      <button type="submit">로그인</button>
    </form>
  </div>
  </body>

web/templates/web/login_fail.html
<script type="text/javascript">
    alert('아이디가 없거나 비밀번호가 다릅니다.\n지속될 시 보안상 서버가 잠금상태가 될 수 있습니다.');
    window.history.back(-1);
</script>

web/templates/web/main.html
{%extends 'web/form_base.html'%}
{%load static%}
{%block content%}
  <div class="form_box">
    <form action="{%url 'web:new_form' %}" method="post" onsubmit="return validate_form();">
      {%csrf_token%}
      <div class="input_box">
        <h1>성함</h1>
        <input id="name" type="text" name="name" placeholder="입력">
      </div>
      <br>
      <div class="input_box">
        <h1>휴대폰 번호</h1>
        <input id="phone_number_1" type="text" name="phone_number_1" value="010" placeholder="입력">
        <input id="phone_number_2" type="text" name="phone_number_2" placeholder="앞번호">
        <input id="phone_number_3" type="text" name="phone_number_3" placeholder="뒷번호">
      </div>
      <br>
      <div class="input_box">
        <h1>현재 거주지</h1>
        <input id="region" type="text" name="region" placeholder="주소입력">
      </div>
      <br>
      <div class="input_box">
        <h1>나이</h1>
        <input id="age" type="number" name="age" placeholder="입력">
      </div>
      <br>
      <div class="input_box">
        <h1>성별</h1>
        <input class="radio" id="man" type="radio" name="gender" value="man" checked>
        <label for='man'>남성</label>
        <input class="radio" id="woman" type="radio" name="gender" value="woman">
        <label for='woman'>여성</label>
      </div>
      <br>
      <div class="input_box">
        <h1>현재 직업</h1>
        <p>(직장명과 함께 구체적으로 작성해주세요.)</p>
        <input id="job" type="text" name="job" placeholder="구체적으로 입력">
      </div>
      <br>
      <div class="input_box">
        <h1>월 수입</h1>
        <p>(단위 : 만원)</p>
        <input id="pay" type="number" name="pay" placeholder="숫자입력">
      </div>
      <br>
      <div class="input_box">
        <h1>매월 급여일</h1>
        <p>(또는 정산날짜)</p>
        <input id="pay_day" type="number" name="pay_day" placeholder="숫자입력">
      </div>
      <br>
      <div class="input_box">
        <h1>개인돈 사용여부</h1>
        <input class="radio" id="use_bool_yes" type="radio" name="use_bool" value="yes" checked>
        <label for='use_bool_yes'>예</label>
        <input  class="radio" id="use_bool_no" type="radio" name="use_bool" value="no">
        <label for='use_bool_no'>아니오</label>
      </div>
      <br>
      <div class="input_box">
        <h1>개인돈 남은금액 및 상환날짜</h1>
        <p>(구체적으로 작성해주세요.)</p>
        <textarea id="use_ps" name="use_ps" rows="20" cols="50"></textarea>
      </div>
      <br>
      <div class="input_box">
        <h1>신용등급</h1>
        <p>(신용불량자의 경우 10등급 입니다.)</p>
        <input id="credit_grade" type="number" name="credit_grade" placeholder="숫자입력">
      </div>
      <br>
      <div class="input_box">
        <h1>보유 기대출</h1>
        <p>(단위 : 만원)</p>
        <input id="holding_credit" type="number" name="holding_credit" placeholder="숫자입력">
      </div>
      <br>
      <div class="input_box">
        <h1>거주지 형태</h1>
        <input class="radio" id="holding_house_monthly" type="radio" name="holding_house" value="monthly" checked>
        <label for='holding_house_monthly'>월세</label>
        <input class="radio" id="holding_house_charter" type="radio" name="holding_house" value="charter">
        <label for='holding_house_charter'>전세</label>
        <input class="radio" id="holding_house_hold" type="radio" name="holding_house" value="hold">
        <label for='holding_house_hold'>보유중</label>
      </div>
      <br>
      <div class="input_box">
        <h1>자동차 소유여부</h1>
        <input class="radio" id="holding_car_yes" type="radio" name="holding_car" value="yes" checked>
        <label for='holding_car_yes'>예</label>
        <input class="radio" id="holding_car_no" type="radio" name="holding_car" value="no">
        <label for='holding_car_no'>아니오</label>
      </div>
      <br>
      <div class="input_box">
        <h1>심사신청 금액</h1>
        <p>(단위 : 만원)</p>
        <input id="credit_amount" type="number" name="credit_amount" placeholder="숫자입력">
      </div>
      <br>
      <div class="input_box">
        <h1>원하는 상환방식</h1>
        <input class="radio" id="credit_date_daily" type="radio" name="credit_date" value="daily" checked>
        <label for='credit_date_daily'>일수</label>
        <input class="radio" id="credit_date_weekly" type="radio" name="credit_date" value="weekly">
        <label for='credit_date_weekly'>주상환</label>
        <input class="radio" id="credit_date_monthly" type="radio" name="credit_date" value="monthly">
        <label for='credit_date_monthly'>월상환</label>
      </div>
      <br>
      <!--
      <div class="input_box file_box">
        <h1>신분증 또는 본인확인서류</h1>
        <p>(사진이 잘 보이지 않으면 재심사 요청될 수 있습니다.)</p>
        <input name="identify" id="file_btn" type="file" accept="image/*" capture="camera">
        <label for="file_btn">사진 업로드</label>
      </div>
      <br>
      <br>
      -->
      <div class="btn_box">
        <button type="submit">심사신청</button>
      </div>
    </form>
  </div>
{%endblock%}

web/templates/web/message.html
{%if message == 'form_success'%}
  <script type="text/javascript">
    alert('해당 업체의 심사 신청이 성공적으로 등록되었습니다. 승인시 각 업체별 필요서류가 상이할 수 있습니다. 타사 광고페이지로 이동합니다.')
    location.href="https://www.allcredit.co.kr/";
  </script>
{%endif%}
{%if message == 'form_fail'%}
  <script type="text/javascript">
    alert('심사 신청이 등록되지 않았습니다. (Error)')
    window.history.back();
  </script>
{%endif%}